version: "3"
services:
  app:
    build: .
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=${NODE_ENV}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./src:/usr/src/app/src
      - ./tests/:/usr/src/app/tests/

  redis:
    image: redis:6
    privileged: true
    volumes:
      - ./redis/data:/data
